version: '2.1'

services:
    mysql-base:
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            MYSQL_DATABASE: nodejsmysqlxtest
            MYSQL_LOG_CONSOLE: 'true'
            MYSQL_PASSWORD: test
            MYSQL_USER: test
        image: mysql/mysql-server:${MYSQL_VERSION:-8.0.3}

    mysql:
        command: mysqld --plugin-load=mysqlx=mysqlx.so
        extends:
            service: mysql-base
        ports:
            - 33060:33060

    mysql-ssl:
        command: mysqld --plugin-load=mysqlx=mysqlx.so --ssl-key=/ssl/key.pem --ssl-cert=/ssl/cert.pem
        extends:
            service: mysql-base
        ports:
            - 33061:33060
        volumes:
            - ./test/fixtures/ssl/server:/ssl:ro

    mysql-no-ssl:
        command: mysqld --plugin-load=mysqlx=mysqlx.so --skip-ssl
        extends:
            service: mysql-base
        ports:
            - 33062:33060

    mysql-sha256:
        command: mysqld --plugin-load=mysqlx=mysqlx.so --default-authentication-plugin=sha256_password
        extends:
            service: mysql-base
        ports:
            - 33063:33060

    mysql-5.7:
        command: mysqld --plugin-load=mysqlx=mysqlx.so
        extends:
            service: mysql-base
        image: mysql/mysql-server:5.7
        ports:
            - 33064:33060

    mysql-5.7-sha256:
        command: mysqld --plugin-load=mysqlx=mysqlx.so --default-authentication-plugin=sha256_password
        extends:
            service: mysql-base
        image: mysql/mysql-server:5.7
        ports:
            - 33065:33060

volumes:
    ssl:
